import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.events': 'Events',
    'nav.news': 'News',
    'nav.stories': 'Stories',
    'nav.discussions': 'Discussions',
    'nav.learningHub': 'Learning Hub',
    'nav.contact': 'Contact',
    'nav.search': 'Search...',
    'nav.menu': 'MENU',
    'nav.followUs': 'Follow Us',
    
    // Home page
    'home.hero.title': 'Connecting Diaspora Communities Worldwide',
    'home.hero.subtitle': 'Join our vibrant community of language cultural exchange, support, and growth for diaspora communities in Portugal.',
    'home.hero.learnMore': 'Learn More',
    'home.hero.upcomingEvents': 'Upcoming Events',
    
    'home.news.title': 'Latest News',
    'home.news.subtitle': 'Stay updated with our community highlights',
    'home.news.featured.title': 'Successful Diaspora Picnic Brings Community Together',
    'home.news.featured.content': 'Our recent Diaspora Picnic was a wonderful celebration of community and cultural exchange. Members from various African and Afro-descendant communities came together, sharing traditional dishes, stories, and creating new connections. The event featured games, music, and meaningful conversations that strengthened our community bonds.',
    'home.news.readMore': 'Read More',
    
    'home.features.title': 'What We Offer',
    'home.features.subtitle': 'Explore our community resources and activities',
    'home.features.events.title': 'Community Events',
    'home.features.events.description': 'Join cultural celebrations, workshops, and networking opportunities.',
    'home.features.events.link': 'View Events',
    'home.features.news.title': 'Local News',
    'home.features.news.description': 'Stay updated with news relevant to diaspora communities.',
    'home.features.news.link': 'Read News',
    'home.features.stories.title': 'Member Stories',
    'home.features.stories.description': 'Read inspiring stories from our community members.',
    'home.features.stories.link': 'Explore Stories',
    'home.features.discussions.title': 'Discussions',
    'home.features.discussions.description': 'Engage in meaningful conversations with community members.',
    'home.features.discussions.link': 'Join Discussions',
    'home.features.learning.title': 'Learning Hub',
    'home.features.learning.description': 'Access educational resources, language courses, and more.',
    'home.features.learning.link': 'Start Learning',
    'home.features.network.title': 'Global Network',
    'home.features.network.description': 'Connect with diaspora communities from around the world.',
    'home.features.network.link': 'Learn More',
    
    'home.upcomingEvents.title': 'Upcoming Events',
    'home.upcomingEvents.viewAll': 'View All',
    'home.upcomingEvents.diasporaPicnic.title': 'Diáspora Picnic',
    'home.upcomingEvents.diasporaPicnic.description': 'Join us for a community picnic featuring games, fellowship, and cultural exchange.',
    'home.upcomingEvents.diasporaPicnic.register': 'Register Now',
    'home.upcomingEvents.africaDay.title': 'Africa Day Celebration',
    'home.upcomingEvents.africaDay.description': 'Celebrate African cultures with concerts, traditional food, DJ sets, dance, and projections.',
    'home.upcomingEvents.languageExchange.title': 'Language Exchange Event',
    'home.upcomingEvents.languageExchange.description': 'Practice language skills and connect with native speakers in a friendly environment.',
    'home.upcomingEvents.learnMore': 'Learn More',
    
    'home.testimonials.title': 'What Our Community Says',
    'home.testimonials.subtitle': 'Hear from members who have found connection and growth through our community',
    'home.testimonials.telma': '"As a writer exploring African identity in Portugal, Intercâmbio Diáspora provided the authentic voices and stories that enriched my work. This community became both my research foundation and my creative inspiration, helping me tell our stories with truth and dignity."',
    'home.testimonials.naky': '"Through Intercâmbio Diáspora, I discovered the hidden African heritage of Lisbon and turned that passion into African Lisbon Tour. This community connected me with historians, storytellers, and cultural guardians who helped me create meaningful experiences that celebrate our presence in this city."',
    'home.testimonials.boni': '"Organizing cultural events became more impactful through Intercâmbio Diáspora\'s network. I found collaborators, venues, and most importantly, an audience that truly appreciates authentic African culture. Together, we create events that educate, celebrate, and unite our diverse diaspora community."',
    
    'home.newsletter.title': 'Stay Connected',
    'home.newsletter.subtitle': 'Join our newsletter to receive updates about events, stories, and community initiatives',
    'home.newsletter.name': 'Name',
    'home.newsletter.namePlaceholder': 'Your name',
    'home.newsletter.email': 'Email',
    'home.newsletter.emailPlaceholder': 'Your email address',
    'home.newsletter.subscribe': 'Subscribe',
    
    'home.contribute.title': 'Support Our Community',
    'home.contribute.subtitle': 'Help us create more opportunities for connection and cultural exchange',
    'home.contribute.shareStory.title': 'Share Your Story',
    'home.contribute.shareStory.description': 'Contribute to our community narrative by sharing your experiences and journey',
    'home.contribute.shareStory.button': 'Share Now',
    'home.contribute.volunteer.title': 'Volunteer',
    'home.contribute.volunteer.description': 'Join our team of volunteers and help organize community events and programs',
    'home.contribute.volunteer.button': 'Get Involved',
    'home.contribute.partner.title': 'Partner With Us',
    'home.contribute.partner.description': 'Collaborate with us to create meaningful impact in our community',
    'home.contribute.partner.button': 'Learn More',
    
    'home.social.title': 'Connect With Us',
    'home.social.instagram': 'Follow us on Instagram',

    // About page
    'about.title': 'About Intercâmbio Diáspora',
    'about.subtitle': 'Connecting African and Afro-descendant communities through cultural exchange, education, and solidarity.',
    'about.mission.title': 'Our Mission',
    'about.mission.content': 'To empower and connect African and Afro-descendant communities across the diaspora by creating inclusive spaces for language learning, cultural exchange, storytelling, and solidarity-building in Portugal and beyond.',
    'about.vision.title': 'Our Vision',
    'about.vision.content': 'We envision a world where diasporic communities thrive through shared knowledge, cultural pride, and meaningful collaboration — building bridges between people, generations, and continents.',
    'about.values.title': 'Our Values',
    'about.values.culturalPride.title': 'Cultural Pride',
    'about.values.culturalPride.content': 'We celebrate the rich diversity of African and Afro-descendant cultures, fostering pride in our heritage and creating spaces for authentic expression.',
    'about.values.community.title': 'Community Connection',
    'about.values.community.content': 'We build strong bonds within the diaspora community, creating a supportive network that spans cultures, languages, and generations.',
    'about.values.knowledge.title': 'Knowledge Sharing',
    'about.values.knowledge.content': 'We facilitate learning exchanges that empower our community, from language skills to cultural knowledge and historical understanding.',
    'about.values.solidarity.title': 'Solidarity',
    'about.values.solidarity.content': 'We stand together in unity, supporting each other\'s growth and well-being while advocating for our collective interests.',
    'about.values.exchange.title': 'Cultural Exchange',
    'about.values.exchange.content': 'We create meaningful opportunities for sharing traditions, stories, and experiences that strengthen our connections and understanding.',
    'about.values.narrative.title': 'Narrative Reclamation',
    'about.values.narrative.content': 'We empower our community to tell their own stories, challenging stereotypes and celebrating the richness of our diverse experiences.',
    'about.story.title': 'Our Story',
    'about.story.content1': 'Intercâmbio Diáspora is a grassroots community platform based in Lisbon that brings together individuals of African descent and allies from around the world to learn, share, and grow together. Through language exchanges, cultural meetups, museum visits, educational workshops, storytelling sessions, and local tours, we foster a deep sense of belonging, pride, and connection.',
    'about.story.content2': 'We celebrate the diversity of the diaspora, while reclaiming narratives and creating opportunities for learning and healing. Whether you\'re new to Portugal or have roots deeply planted, our community offers a warm space to connect through African heritage, lived experiences, and collective resilience.',
    'about.story.content3': 'Join us to practice Portuguese, explore local history, attend diaspora events, share your story, and find support within a global family grounded in culture and community.',
    'about.getInvolved.title': 'Get Involved',
    'about.getInvolved.events.title': 'Join Our Events',
    'about.getInvolved.events.content': 'Participate in our language exchanges, cultural meetups, workshops, and community gatherings. Connect with others and share experiences.',
    'about.getInvolved.events.button': 'View Events',
    'about.getInvolved.story.title': 'Share Your Story',
    'about.getInvolved.story.content': 'Contribute to our community\'s narrative by sharing your experiences, skills, and cultural knowledge. Every voice matters.',
    'about.getInvolved.story.button': 'Get Started',
    'about.getInvolved.partner.title': 'Partner With Us',
    'about.getInvolved.partner.content': 'Collaborate with us to create impactful programs and events that serve the African and Afro-descendant diaspora community.',
    'about.getInvolved.partner.button': 'Contact Us',
    'about.contact.title': 'Contact Us',
    'about.contact.subtitle': 'We\'d love to hear from you! Reach out with questions, ideas, or to learn more about our community and events.',
    'about.contact.email': 'Email',
    'about.contact.events': 'Events',
    'about.contact.eventsDesc1': 'Regular meetups and activities throughout Lisbon',
    'about.contact.eventsDesc2': 'Check our events calendar for details',
    'about.contact.location': 'Location',
    'about.contact.locationDesc1': 'Lisbon, Portugal',
    'about.contact.locationDesc2': 'Various community spaces across the city',
    'about.contact.form.title': 'Send Us a Message',
    'about.contact.form.name': 'Name',
    'about.contact.form.email': 'Email',
    'about.contact.form.subject': 'Subject',
    'about.contact.form.message': 'Message',
    'about.contact.form.send': 'Send Message',

    // Events page
    'events.title': 'Community Events',
    'events.subtitle': 'Join our vibrant community gatherings, workshops, and celebrations. Connect, learn, and grow with fellow diaspora members.',
    'events.search': 'Search events...',
    'events.upcoming': 'Upcoming Events',
    'events.past': 'Past Events',
    'events.showLess': 'Show Less',
    'events.showAll': 'Show All',
    'events.registerNow': 'Register Now',
    'events.noEvents': 'No events found matching your criteria',
    'events.noEventsDesc': 'Try adjusting your search or filter settings',
    'events.until': 'Until',

    // News page
    'news.title': 'Latest News',
    'news.subtitle': 'Stay updated with the latest news and events from Intercâmbio Diáspora.',
    'news.search': 'Search news...',
    'news.readFullArticle': 'Read Full Article',
    'news.backToNews': '← Back to News',
    'news.shareArticle': 'Share this article',
    'news.noArticles': 'No articles found matching your criteria',
    'news.noArticlesDesc': 'Try adjusting your search or filter settings',
    'news.by': 'By',

    // Stories page
    'stories.title': 'Diaspora Stories: Our Voices, Our Journeys',
    'stories.subtitle': 'Every story in our diaspora community weaves a unique thread into the fabric of our shared experience. Through these narratives, we celebrate our diversity, honor our heritage, and build bridges of understanding.',
    'stories.shareStory': 'Share Your Story',
    'stories.search': 'Search stories...',
    'stories.popularThemes': 'Popular Themes:',
    'stories.readMore': 'Read More',
    'stories.form.title': 'Share Your Story',
    'stories.form.name': 'Your Name',
    'stories.form.storyTitle': 'Story Title',
    'stories.form.story': 'Your Story',
    'stories.form.storyPlaceholder': 'Share your journey, experiences, and reflections...',
    'stories.form.images': 'Upload Images (optional)',
    'stories.form.cancel': 'Cancel',
    'stories.form.submit': 'Submit Story',

    // Discussions page
    'discussions.title': 'Community Engagement',
    'discussions.subtitle': 'Connect, share, and engage with our vibrant diaspora community through various channels and activities.',
    'discussions.participate.title': 'Participate & Share',
    'discussions.highlights.title': 'Community Highlights',
    'discussions.connect.title': 'Connect With Us',
    'discussions.participate': 'Participate',
    'discussions.viewOnInstagram': 'View on Instagram',
    'discussions.followUs': 'Follow Us',

    // Learning Hub page
    'learningHub.title': 'Learning Hub',
    'learningHub.subtitle': 'Access resources, guides, and support for your journey in Portugal.',
    'learningHub.search': 'Search resources...',
    'learningHub.contactInfo': 'Contact for more information',
    'learningHub.gettingStarted': 'Getting Started in Portugal',
    'learningHub.gettingStartedDesc': 'Essential resources for newcomers to Portugal',
    'learningHub.language': 'Language Learning Resources',
    'learningHub.languageDesc': 'Tools and resources for learning Portuguese',
    'learningHub.cultural': 'Cultural Integration',
    'learningHub.culturalDesc': 'Resources for understanding and celebrating cultural heritage',
    'learningHub.professional': 'Professional Development',
    'learningHub.professionalDesc': 'Career advancement and business resources',
    'learningHub.family': 'Family & Education',
    'learningHub.familyDesc': 'Resources for families and educational support',

    // Contact page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team for questions, partnerships, or to learn more about our programs and services.',
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Have questions or want to get involved? Reach out to us using any of the methods below.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.address': 'Address',
    'contact.info.hours': 'Office Hours',
    'contact.info.hoursDesc': 'Monday - Friday: 9:00 AM - 5:00 PM\nSaturday: 10:00 AM - 2:00 PM (by appointment)',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.required': '*',
    'contact.form.send': 'Send Message',
    'contact.location.title': 'Our Location',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.what.question': 'What is Intercâmbio Diáspora?',
    'contact.faq.what.answer': 'We are a grassroots community platform based in Lisbon that brings together individuals of African descent and allies from around the world to learn, share, and grow together through language exchanges, cultural meetups, museum visits, educational workshops, storytelling sessions, and local tours.',
    'contact.faq.participate.question': 'How can I participate in your events?',
    'contact.faq.participate.answer': 'You can join our events by checking our Events page for upcoming activities and registering through our online form. We offer various activities including language exchanges, cultural meetups, workshops, and community gatherings.',
    'contact.faq.diaspora.question': 'Do I need to be from the African diaspora to participate?',
    'contact.faq.diaspora.answer': 'While our focus is on connecting African and Afro-descendant communities, we welcome allies and anyone interested in learning about and celebrating African cultures, fostering cross-cultural understanding and solidarity.',
    'contact.faq.support.question': 'How can I support or partner with Intercâmbio Diáspora?',
    'contact.faq.support.answer': 'There are several ways to support our work: attend our events, volunteer your skills, share your stories, or partner with us on community initiatives. Contact us through our form or email to discuss collaboration opportunities.',
    'contact.faq.languages.question': 'What languages are used in your events?',
    'contact.faq.languages.answer': 'Our events primarily use Portuguese and English, but we celebrate multilingualism and often incorporate other languages through our cultural exchange activities and language learning programs.',

    // Privacy Policy page
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated:',
    'privacy.intro.title': 'Introduction',
    'privacy.intro.content': 'Intercâmbio Diáspora ("we," "our," or "us") respects your privacy and is committed to protecting your personal data. This privacy policy explains how we collect, use, and protect your information when you use our website and services.',
    'privacy.collect.title': 'Information We Collect',
    'privacy.collect.content': 'We collect information that you provide directly to us, including:',
    'privacy.collect.direct': 'Name and contact information\nAccount credentials\nProfile information\nCommunication preferences\nEvent participation details',
    'privacy.collect.auto': 'We also automatically collect certain information when you visit our website, including:',
    'privacy.collect.autoList': 'Device and browser information\nIP address and location data\nUsage data and cookies\nWebsite interaction information',
    'privacy.use.title': 'How We Use Your Information',
    'privacy.use.content': 'We use your information to:',
    'privacy.use.list': 'Provide and improve our services\nCommunicate with you about events and updates\nProcess event registrations and memberships\nPersonalize your experience\nEnsure website security and prevent fraud\nComply with legal obligations',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.content1': 'We use cookies and similar tracking technologies to enhance your experience on our website. Cookies are small data files stored on your device that help us improve our services and your experience.',
    'privacy.cookies.content2': 'You can control cookie preferences through your browser settings. However, disabling cookies may limit your ability to use certain features of our website.',
    'privacy.sharing.title': 'Data Sharing and Disclosure',
    'privacy.sharing.content': 'We do not sell your personal information. We may share your information with:',
    'privacy.sharing.list': 'Service providers who assist in our operations\nPartners for specific events or programs\nLegal authorities when required by law\nOther users with your consent (e.g., public profile information)',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.content': 'You have the right to:',
    'privacy.rights.list': 'Access your personal data\nCorrect inaccurate data\nRequest deletion of your data\nObject to data processing\nWithdraw consent\nRequest data portability',
    'privacy.security.title': 'Security',
    'privacy.security.content': 'We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.',
    'privacy.changes.title': 'Changes to This Policy',
    'privacy.changes.content': 'We may update this privacy policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the "Last updated" date.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.content': 'If you have questions about this privacy policy or our practices, please contact us at:',
    'privacy.contact.email': 'Email:',
    'privacy.contact.address': 'Address:',

    // Terms of Service page
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last updated:',
    'terms.agreement.title': 'Agreement to Terms',
    'terms.agreement.content': 'By accessing or using the Intercâmbio Diáspora website and services, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access our services.',
    'terms.use.title': 'Use of Services',
    'terms.use.content': 'Our services are intended for:',
    'terms.use.list': 'Community members seeking to connect with the African and Afro-descendant diaspora\nParticipants in cultural exchange and educational programs\nUsers interested in our events and activities',
    'terms.use.lawful': 'You agree to use our services only for lawful purposes and in accordance with these Terms.',
    'terms.accounts.title': 'User Accounts',
    'terms.accounts.content': 'When creating an account, you agree to:',
    'terms.accounts.list': 'Provide accurate and complete information\nMaintain the security of your account credentials\nPromptly update any changes to your information\nAccept responsibility for all activities under your account',
    'terms.guidelines.title': 'Community Guidelines',
    'terms.guidelines.content': 'Users must:',
    'terms.guidelines.list': 'Respect other community members\nAvoid harmful or discriminatory behavior\nNot post inappropriate or offensive content\nFollow event and program guidelines\nMaintain confidentiality when required',
    'terms.ip.title': 'Intellectual Property',
    'terms.ip.content': 'All content on our website, including text, graphics, logos, and images, is the property of Intercâmbio Diáspora or our licensors and is protected by copyright and other intellectual property laws.',
    'terms.events.title': 'Events and Programs',
    'terms.events.content': 'Participation in events and programs is subject to:',
    'terms.events.list': 'Registration requirements and deadlines\nPayment of any applicable fees\nAdherence to event-specific guidelines\nCancellation and refund policies',
    'terms.liability.title': 'Limitation of Liability',
    'terms.liability.content': 'Intercâmbio Diáspora shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use or inability to use our services.',
    'terms.changes.title': 'Changes to Terms',
    'terms.changes.content': 'We reserve the right to modify these terms at any time. We will notify users of any material changes through our website or email.',
    'terms.contact.title': 'Contact Information',
    'terms.contact.content': 'For questions about these Terms of Service, please contact us at:',
    'terms.contact.email': 'Email:',
    'terms.contact.address': 'Address:',
    
    // Footer
    'footer.description': 'Connecting diaspora communities through cultural exchange, education, and support.',
    'footer.quickLinks': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.contact': 'Contact Us',
    'footer.copyright': 'All rights reserved.',
    'footer.cookies.text': 'This website uses cookies to enhance the user experience. By continuing to browse the site, you agree to our use of cookies.',
    'footer.cookies.learnMore': 'Learn more',
    'footer.cookies.accept': 'Accept',
    'footer.cookies.decline': 'Decline',

    // Common
    'common.all': 'All',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.share': 'Share',
    'common.like': 'Like',
    'common.comment': 'Comment',
    'common.readMore': 'Read More',
    'common.showMore': 'Show More',
    'common.showLess': 'Show Less',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.events': 'Eventos',
    'nav.news': 'Notícias',
    'nav.stories': 'Histórias',
    'nav.discussions': 'Discussões',
    'nav.learningHub': 'Centro de Aprendizagem',
    'nav.contact': 'Contacto',
    'nav.search': 'Pesquisar...',
    'nav.menu': 'MENU',
    'nav.followUs': 'Siga-nos',
    
    // Home page
    'home.hero.title': 'Conectando Comunidades da Diáspora Mundial',
    'home.hero.subtitle': 'Junte-se à nossa vibrante comunidade de intercâmbio cultural linguístico, apoio e crescimento para comunidades da diáspora em Portugal.',
    'home.hero.learnMore': 'Saber Mais',
    'home.hero.upcomingEvents': 'Próximos Eventos',
    
    'home.news.title': 'Últimas Notícias',
    'home.news.subtitle': 'Mantenha-se atualizado com os destaques da nossa comunidade',
    'home.news.featured.title': 'Piquenique da Diáspora Bem-Sucedido Une a Comunidade',
    'home.news.featured.content': 'O nosso recente Piquenique da Diáspora foi uma maravilhosa celebração de comunidade e intercâmbio cultural. Membros de várias comunidades africanas e afrodescendentes reuniram-se, partilhando pratos tradicionais, histórias e criando novas conexões. O evento incluiu jogos, música e conversas significativas que fortaleceram os laços comunitários.',
    'home.news.readMore': 'Ler Mais',
    
    'home.features.title': 'O Que Oferecemos',
    'home.features.subtitle': 'Explore os nossos recursos e atividades comunitárias',
    'home.features.events.title': 'Eventos Comunitários',
    'home.features.events.description': 'Participe em celebrações culturais, workshops e oportunidades de networking.',
    'home.features.events.link': 'Ver Eventos',
    'home.features.news.title': 'Notícias Locais',
    'home.features.news.description': 'Mantenha-se atualizado com notícias relevantes para as comunidades da diáspora.',
    'home.features.news.link': 'Ler Notícias',
    'home.features.stories.title': 'Histórias dos Membros',
    'home.features.stories.description': 'Leia histórias inspiradoras dos nossos membros da comunidade.',
    'home.features.stories.link': 'Explorar Histórias',
    'home.features.discussions.title': 'Discussões',
    'home.features.discussions.description': 'Participe em conversas significativas com membros da comunidade.',
    'home.features.discussions.link': 'Juntar-se às Discussões',
    'home.features.learning.title': 'Centro de Aprendizagem',
    'home.features.learning.description': 'Aceda a recursos educacionais, cursos de idiomas e muito mais.',
    'home.features.learning.link': 'Começar a Aprender',
    'home.features.network.title': 'Rede Global',
    'home.features.network.description': 'Conecte-se com comunidades da diáspora de todo o mundo.',
    'home.features.network.link': 'Saber Mais',
    
    'home.upcomingEvents.title': 'Próximos Eventos',
    'home.upcomingEvents.viewAll': 'Ver Todos',
    'home.upcomingEvents.diasporaPicnic.title': 'Piquenique da Diáspora',
    'home.upcomingEvents.diasporaPicnic.description': 'Junte-se a nós para um piquenique comunitário com jogos, convívio e intercâmbio cultural.',
    'home.upcomingEvents.diasporaPicnic.register': 'Inscrever-se Agora',
    'home.upcomingEvents.africaDay.title': 'Celebração do Dia de África',
    'home.upcomingEvents.africaDay.description': 'Celebre as culturas africanas com concertos, comida tradicional, DJ sets, dança e projeções.',
    'home.upcomingEvents.languageExchange.title': 'Evento de Intercâmbio de Idiomas',
    'home.upcomingEvents.languageExchange.description': 'Pratique competências linguísticas e conecte-se com falantes nativos num ambiente amigável.',
    'home.upcomingEvents.learnMore': 'Saber Mais',
    
    'home.testimonials.title': 'O Que a Nossa Comunidade Diz',
    'home.testimonials.subtitle': 'Ouça membros que encontraram conexão e crescimento através da nossa comunidade',
    'home.testimonials.telma': '"Como escritora explorando a identidade africana em Portugal, o Intercâmbio Diáspora forneceu as vozes autênticas e histórias que enriqueceram o meu trabalho. Esta comunidade tornou-se tanto a minha base de pesquisa quanto a minha inspiração criativa, ajudando-me a contar as nossas histórias com verdade e dignidade."',
    'home.testimonials.naky': '"Através do Intercâmbio Diáspora, descobri o património africano oculto de Lisboa e transformei essa paixão no African Lisbon Tour. Esta comunidade conectou-me com historiadores, contadores de histórias e guardiões culturais que me ajudaram a criar experiências significativas que celebram a nossa presença nesta cidade."',
    'home.testimonials.boni': '"Organizar eventos culturais tornou-se mais impactante através da rede do Intercâmbio Diáspora. Encontrei colaboradores, locais e, mais importante, um público que verdadeiramente aprecia a cultura africana autêntica. Juntos, criamos eventos que educam, celebram e unem a nossa diversa comunidade da diáspora."',
    
    'home.newsletter.title': 'Mantenha-se Conectado',
    'home.newsletter.subtitle': 'Junte-se à nossa newsletter para receber atualizações sobre eventos, histórias e iniciativas comunitárias',
    'home.newsletter.name': 'Nome',
    'home.newsletter.namePlaceholder': 'O seu nome',
    'home.newsletter.email': 'Email',
    'home.newsletter.emailPlaceholder': 'O seu endereço de email',
    'home.newsletter.subscribe': 'Subscrever',
    
    'home.contribute.title': 'Apoie a Nossa Comunidade',
    'home.contribute.subtitle': 'Ajude-nos a criar mais oportunidades de conexão e intercâmbio cultural',
    'home.contribute.shareStory.title': 'Partilhe a Sua História',
    'home.contribute.shareStory.description': 'Contribua para a narrativa da nossa comunidade partilhando as suas experiências e jornada',
    'home.contribute.shareStory.button': 'Partilhar Agora',
    'home.contribute.volunteer.title': 'Voluntário',
    'home.contribute.volunteer.description': 'Junte-se à nossa equipa de voluntários e ajude a organizar eventos e programas comunitários',
    'home.contribute.volunteer.button': 'Envolver-se',
    'home.contribute.partner.title': 'Seja Nosso Parceiro',
    'home.contribute.partner.description': 'Colabore connosco para criar um impacto significativo na nossa comunidade',
    'home.contribute.partner.button': 'Saber Mais',
    
    'home.social.title': 'Conecte-se Connosco',
    'home.social.instagram': 'Siga-nos no Instagram',

    // About page
    'about.title': 'Sobre o Intercâmbio Diáspora',
    'about.subtitle': 'Conectando comunidades africanas e afrodescendentes através de intercâmbio cultural, educação e solidariedade.',
    'about.mission.title': 'A Nossa Missão',
    'about.mission.content': 'Capacitar e conectar comunidades africanas e afrodescendentes em toda a diáspora, criando espaços inclusivos para aprendizagem de idiomas, intercâmbio cultural, narrativa e construção de solidariedade em Portugal e além.',
    'about.vision.title': 'A Nossa Visão',
    'about.vision.content': 'Vislumbramos um mundo onde as comunidades diaspóricas prosperam através do conhecimento partilhado, orgulho cultural e colaboração significativa — construindo pontes entre pessoas, gerações e continentes.',
    'about.values.title': 'Os Nossos Valores',
    'about.values.culturalPride.title': 'Orgulho Cultural',
    'about.values.culturalPride.content': 'Celebramos a rica diversidade das culturas africanas e afrodescendentes, fomentando o orgulho na nossa herança e criando espaços para expressão autêntica.',
    'about.values.community.title': 'Conexão Comunitária',
    'about.values.community.content': 'Construímos laços fortes dentro da comunidade da diáspora, criando uma rede de apoio que abrange culturas, idiomas e gerações.',
    'about.values.knowledge.title': 'Partilha de Conhecimento',
    'about.values.knowledge.content': 'Facilitamos intercâmbios de aprendizagem que capacitam a nossa comunidade, desde competências linguísticas até conhecimento cultural e compreensão histórica.',
    'about.values.solidarity.title': 'Solidariedade',
    'about.values.solidarity.content': 'Permanecemos unidos em unidade, apoiando o crescimento e bem-estar uns dos outros enquanto defendemos os nossos interesses coletivos.',
    'about.values.exchange.title': 'Intercâmbio Cultural',
    'about.values.exchange.content': 'Criamos oportunidades significativas para partilhar tradições, histórias e experiências que fortalecem as nossas conexões e compreensão.',
    'about.values.narrative.title': 'Reclamação Narrativa',
    'about.values.narrative.content': 'Capacitamos a nossa comunidade para contar as suas próprias histórias, desafiando estereótipos e celebrando a riqueza das nossas experiências diversas.',
    'about.story.title': 'A Nossa História',
    'about.story.content1': 'O Intercâmbio Diáspora é uma plataforma comunitária de base em Lisboa que reúne indivíduos de ascendência africana e aliados de todo o mundo para aprender, partilhar e crescer juntos. Através de intercâmbios linguísticos, encontros culturais, visitas a museus, workshops educacionais, sessões de narrativa e tours locais, fomentamos um profundo sentido de pertença, orgulho e conexão.',
    'about.story.content2': 'Celebramos a diversidade da diáspora, enquanto reclamamos narrativas e criamos oportunidades para aprendizagem e cura. Seja novo em Portugal ou com raízes profundamente plantadas, a nossa comunidade oferece um espaço caloroso para conectar através da herança africana, experiências vividas e resistência coletiva.',
    'about.story.content3': 'Junte-se a nós para praticar português, explorar a história local, participar em eventos da diáspora, partilhar a sua história e encontrar apoio dentro de uma família global baseada na cultura e comunidade.',
    'about.getInvolved.title': 'Envolva-se',
    'about.getInvolved.events.title': 'Participe nos Nossos Eventos',
    'about.getInvolved.events.content': 'Participe nos nossos intercâmbios linguísticos, encontros culturais, workshops e reuniões comunitárias. Conecte-se com outros e partilhe experiências.',
    'about.getInvolved.events.button': 'Ver Eventos',
    'about.getInvolved.story.title': 'Partilhe a Sua História',
    'about.getInvolved.story.content': 'Contribua para a narrativa da nossa comunidade partilhando as suas experiências, competências e conhecimento cultural. Cada voz importa.',
    'about.getInvolved.story.button': 'Começar',
    'about.getInvolved.partner.title': 'Seja Nosso Parceiro',
    'about.getInvolved.partner.content': 'Colabore connosco para criar programas e eventos impactantes que sirvam a comunidade da diáspora africana e afrodescendente.',
    'about.getInvolved.partner.button': 'Contacte-nos',
    'about.contact.title': 'Contacte-nos',
    'about.contact.subtitle': 'Adoraríamos ouvir de si! Entre em contacto com perguntas, ideias ou para saber mais sobre a nossa comunidade e eventos.',
    'about.contact.email': 'Email',
    'about.contact.events': 'Eventos',
    'about.contact.eventsDesc1': 'Encontros regulares e atividades por toda Lisboa',
    'about.contact.eventsDesc2': 'Consulte o nosso calendário de eventos para detalhes',
    'about.contact.location': 'Localização',
    'about.contact.locationDesc1': 'Lisboa, Portugal',
    'about.contact.locationDesc2': 'Vários espaços comunitários pela cidade',
    'about.contact.form.title': 'Envie-nos uma Mensagem',
    'about.contact.form.name': 'Nome',
    'about.contact.form.email': 'Email',
    'about.contact.form.subject': 'Assunto',
    'about.contact.form.message': 'Mensagem',
    'about.contact.form.send': 'Enviar Mensagem',

    // Events page
    'events.title': 'Eventos Comunitários',
    'events.subtitle': 'Junte-se às nossas vibrantes reuniões comunitárias, workshops e celebrações. Conecte-se, aprenda e cresça com outros membros da diáspora.',
    'events.search': 'Pesquisar eventos...',
    'events.upcoming': 'Próximos Eventos',
    'events.past': 'Eventos Passados',
    'events.showLess': 'Mostrar Menos',
    'events.showAll': 'Mostrar Todos',
    'events.registerNow': 'Inscrever-se Agora',
    'events.noEvents': 'Nenhum evento encontrado que corresponda aos seus critérios',
    'events.noEventsDesc': 'Tente ajustar as suas configurações de pesquisa ou filtro',
    'events.until': 'Até',

    // News page
    'news.title': 'Últimas Notícias',
    'news.subtitle': 'Mantenha-se atualizado com as últimas notícias e eventos do Intercâmbio Diáspora.',
    'news.search': 'Pesquisar notícias...',
    'news.readFullArticle': 'Ler Artigo Completo',
    'news.backToNews': '← Voltar às Notícias',
    'news.shareArticle': 'Partilhar este artigo',
    'news.noArticles': 'Nenhum artigo encontrado que corresponda aos seus critérios',
    'news.noArticlesDesc': 'Tente ajustar as suas configurações de pesquisa ou filtro',
    'news.by': 'Por',

    // Stories page
    'stories.title': 'Histórias da Diáspora: As Nossas Vozes, As Nossas Jornadas',
    'stories.subtitle': 'Cada história na nossa comunidade da diáspora tece um fio único no tecido da nossa experiência partilhada. Através destas narrativas, celebramos a nossa diversidade, honramos a nossa herança e construímos pontes de compreensão.',
    'stories.shareStory': 'Partilhe a Sua História',
    'stories.search': 'Pesquisar histórias...',
    'stories.popularThemes': 'Temas Populares:',
    'stories.readMore': 'Ler Mais',
    'stories.form.title': 'Partilhe a Sua História',
    'stories.form.name': 'O Seu Nome',
    'stories.form.storyTitle': 'Título da História',
    'stories.form.story': 'A Sua História',
    'stories.form.storyPlaceholder': 'Partilhe a sua jornada, experiências e reflexões...',
    'stories.form.images': 'Carregar Imagens (opcional)',
    'stories.form.cancel': 'Cancelar',
    'stories.form.submit': 'Submeter História',

    // Discussions page
    'discussions.title': 'Envolvimento Comunitário',
    'discussions.subtitle': 'Conecte-se, partilhe e envolva-se com a nossa vibrante comunidade da diáspora através de vários canais e atividades.',
    'discussions.participate.title': 'Participe e Partilhe',
    'discussions.highlights.title': 'Destaques da Comunidade',
    'discussions.connect.title': 'Conecte-se Connosco',
    'discussions.participate': 'Participar',
    'discussions.viewOnInstagram': 'Ver no Instagram',
    'discussions.followUs': 'Siga-nos',

    // Learning Hub page
    'learningHub.title': 'Centro de Aprendizagem',
    'learningHub.subtitle': 'Aceda a recursos, guias e apoio para a sua jornada em Portugal.',
    'learningHub.search': 'Pesquisar recursos...',
    'learningHub.contactInfo': 'Contacte para mais informações',
    'learningHub.gettingStarted': 'Começar em Portugal',
    'learningHub.gettingStartedDesc': 'Recursos essenciais para recém-chegados a Portugal',
    'learningHub.language': 'Recursos de Aprendizagem de Idiomas',
    'learningHub.languageDesc': 'Ferramentas e recursos para aprender português',
    'learningHub.cultural': 'Integração Cultural',
    'learningHub.culturalDesc': 'Recursos para compreender e celebrar a herança cultural',
    'learningHub.professional': 'Desenvolvimento Profissional',
    'learningHub.professionalDesc': 'Avanço na carreira e recursos empresariais',
    'learningHub.family': 'Família e Educação',
    'learningHub.familyDesc': 'Recursos para famílias e apoio educacional',

    // Contact page
    'contact.title': 'Contacte-nos',
    'contact.subtitle': 'Entre em contacto com a nossa equipa para perguntas, parcerias ou para saber mais sobre os nossos programas e serviços.',
    'contact.info.title': 'Informações de Contacto',
    'contact.info.subtitle': 'Tem perguntas ou quer envolver-se? Entre em contacto connosco usando qualquer um dos métodos abaixo.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Telefone',
    'contact.info.address': 'Morada',
    'contact.info.hours': 'Horário de Funcionamento',
    'contact.info.hoursDesc': 'Segunda - Sexta: 9:00 - 17:00\nSábado: 10:00 - 14:00 (por marcação)',
    'contact.form.title': 'Envie-nos uma Mensagem',
    'contact.form.name': 'O Seu Nome',
    'contact.form.email': 'O Seu Email',
    'contact.form.subject': 'Assunto',
    'contact.form.message': 'Mensagem',
    'contact.form.required': '*',
    'contact.form.send': 'Enviar Mensagem',
    'contact.location.title': 'A Nossa Localização',
    'contact.faq.title': 'Perguntas Frequentes',
    'contact.faq.what.question': 'O que é o Intercâmbio Diáspora?',
    'contact.faq.what.answer': 'Somos uma plataforma comunitária de base em Lisboa que reúne indivíduos de ascendência africana e aliados de todo o mundo para aprender, partilhar e crescer juntos através de intercâmbios linguísticos, encontros culturais, visitas a museus, workshops educacionais, sessões de narrativa e tours locais.',
    'contact.faq.participate.question': 'Como posso participar nos vossos eventos?',
    'contact.faq.participate.answer': 'Pode juntar-se aos nossos eventos consultando a nossa página de Eventos para atividades próximas e inscrevendo-se através do nosso formulário online. Oferecemos várias atividades incluindo intercâmbios linguísticos, encontros culturais, workshops e reuniões comunitárias.',
    'contact.faq.diaspora.question': 'Preciso ser da diáspora africana para participar?',
    'contact.faq.diaspora.answer': 'Embora o nosso foco seja conectar comunidades africanas e afrodescendentes, damos as boas-vindas a aliados e qualquer pessoa interessada em aprender sobre e celebrar culturas africanas, fomentando compreensão e solidariedade intercultural.',
    'contact.faq.support.question': 'Como posso apoiar ou fazer parceria com o Intercâmbio Diáspora?',
    'contact.faq.support.answer': 'Há várias maneiras de apoiar o nosso trabalho: participar nos nossos eventos, voluntariar as suas competências, partilhar as suas histórias ou fazer parceria connosco em iniciativas comunitárias. Contacte-nos através do nosso formulário ou email para discutir oportunidades de colaboração.',
    'contact.faq.languages.question': 'Que idiomas são usados nos vossos eventos?',
    'contact.faq.languages.answer': 'Os nossos eventos usam principalmente português e inglês, mas celebramos o multilinguismo e frequentemente incorporamos outros idiomas através das nossas atividades de intercâmbio cultural e programas de aprendizagem de idiomas.',

    // Privacy Policy page
    'privacy.title': 'Política de Privacidade',
    'privacy.lastUpdated': 'Última atualização:',
    'privacy.intro.title': 'Introdução',
    'privacy.intro.content': 'O Intercâmbio Diáspora ("nós", "nosso" ou "nos") respeita a sua privacidade e está comprometido em proteger os seus dados pessoais. Esta política de privacidade explica como recolhemos, usamos e protegemos as suas informações quando usa o nosso website e serviços.',
    'privacy.collect.title': 'Informações que Recolhemos',
    'privacy.collect.content': 'Recolhemos informações que nos fornece diretamente, incluindo:',
    'privacy.collect.direct': 'Nome e informações de contacto\nCredenciais de conta\nInformações de perfil\nPreferências de comunicação\nDetalhes de participação em eventos',
    'privacy.collect.auto': 'Também recolhemos automaticamente certas informações quando visita o nosso website, incluindo:',
    'privacy.collect.autoList': 'Informações do dispositivo e navegador\nEndereço IP e dados de localização\nDados de uso e cookies\nInformações de interação com o website',
    'privacy.use.title': 'Como Usamos as Suas Informações',
    'privacy.use.content': 'Usamos as suas informações para:',
    'privacy.use.list': 'Fornecer e melhorar os nossos serviços\nComunicar consigo sobre eventos e atualizações\nProcessar inscrições em eventos e membros\nPersonalizar a sua experiência\nGarantir a segurança do website e prevenir fraude\nCumprir obrigações legais',
    'privacy.cookies.title': 'Cookies',
    'privacy.cookies.content1': 'Usamos cookies e tecnologias de rastreamento similares para melhorar a sua experiência no nosso website. Cookies são pequenos ficheiros de dados armazenados no seu dispositivo que nos ajudam a melhorar os nossos serviços e a sua experiência.',
    'privacy.cookies.content2': 'Pode controlar as preferências de cookies através das configurações do seu navegador. No entanto, desativar cookies pode limitar a sua capacidade de usar certas funcionalidades do nosso website.',
    'privacy.sharing.title': 'Partilha e Divulgação de Dados',
    'privacy.sharing.content': 'Não vendemos as suas informações pessoais. Podemos partilhar as suas informações com:',
    'privacy.sharing.list': 'Fornecedores de serviços que auxiliam nas nossas operações\nParceiros para eventos ou programas específicos\nAutoridades legais quando exigido por lei\nOutros utilizadores com o seu consentimento (ex: informações de perfil público)',
    'privacy.rights.title': 'Os Seus Direitos',
    'privacy.rights.content': 'Tem o direito de:',
    'privacy.rights.list': 'Aceder aos seus dados pessoais\nCorrigir dados imprecisos\nSolicitar a eliminação dos seus dados\nOpor-se ao processamento de dados\nRetirar o consentimento\nSolicitar portabilidade de dados',
    'privacy.security.title': 'Segurança',
    'privacy.security.content': 'Implementamos medidas técnicas e organizacionais apropriadas para proteger as suas informações pessoais. No entanto, nenhum método de transmissão pela Internet é 100% seguro, e não podemos garantir segurança absoluta.',
    'privacy.changes.title': 'Alterações a Esta Política',
    'privacy.changes.content': 'Podemos atualizar esta política de privacidade de tempos em tempos. Notificaremos sobre quaisquer alterações publicando a nova política nesta página e atualizando a data de "Última atualização".',
    'privacy.contact.title': 'Contacte-nos',
    'privacy.contact.content': 'Se tiver perguntas sobre esta política de privacidade ou as nossas práticas, contacte-nos em:',
    'privacy.contact.email': 'Email:',
    'privacy.contact.address': 'Morada:',

    // Terms of Service page
    'terms.title': 'Termos de Serviço',
    'terms.lastUpdated': 'Última atualização:',
    'terms.agreement.title': 'Acordo com os Termos',
    'terms.agreement.content': 'Ao aceder ou usar o website e serviços do Intercâmbio Diáspora, concorda em estar vinculado a estes Termos de Serviço. Se discordar de qualquer parte destes termos, não pode aceder aos nossos serviços.',
    'terms.use.title': 'Uso dos Serviços',
    'terms.use.content': 'Os nossos serviços destinam-se a:',
    'terms.use.list': 'Membros da comunidade que procuram conectar-se com a diáspora africana e afrodescendente\nParticipantes em programas de intercâmbio cultural e educacional\nUtilizadores interessados nos nossos eventos e atividades',
    'terms.use.lawful': 'Concorda em usar os nossos serviços apenas para fins legais e de acordo com estes Termos.',
    'terms.accounts.title': 'Contas de Utilizador',
    'terms.accounts.content': 'Ao criar uma conta, concorda em:',
    'terms.accounts.list': 'Fornecer informações precisas e completas\nManter a segurança das suas credenciais de conta\nAtualizar prontamente quaisquer alterações às suas informações\nAceitar responsabilidade por todas as atividades sob a sua conta',
    'terms.guidelines.title': 'Diretrizes da Comunidade',
    'terms.guidelines.content': 'Os utilizadores devem:',
    'terms.guidelines.list': 'Respeitar outros membros da comunidade\nEvitar comportamento prejudicial ou discriminatório\nNão publicar conteúdo inadequado ou ofensivo\nSeguir as diretrizes de eventos e programas\nManter confidencialidade quando necessário',
    'terms.ip.title': 'Propriedade Intelectual',
    'terms.ip.content': 'Todo o conteúdo no nosso website, incluindo texto, gráficos, logótipos e imagens, é propriedade do Intercâmbio Diáspora ou dos nossos licenciadores e está protegido por direitos autorais e outras leis de propriedade intelectual.',
    'terms.events.title': 'Eventos e Programas',
    'terms.events.content': 'A participação em eventos e programas está sujeita a:',
    'terms.events.list': 'Requisitos de inscrição e prazos\nPagamento de quaisquer taxas aplicáveis\nAderência às diretrizes específicas do evento\nPolíticas de cancelamento e reembolso',
    'terms.liability.title': 'Limitação de Responsabilidade',
    'terms.liability.content': 'O Intercâmbio Diáspora não será responsável por quaisquer danos indiretos, incidentais, especiais, consequenciais ou punitivos resultantes do seu uso ou incapacidade de usar os nossos serviços.',
    'terms.changes.title': 'Alterações aos Termos',
    'terms.changes.content': 'Reservamo-nos o direito de modificar estes termos a qualquer momento. Notificaremos os utilizadores de quaisquer alterações materiais através do nosso website ou email.',
    'terms.contact.title': 'Informações de Contacto',
    'terms.contact.content': 'Para perguntas sobre estes Termos de Serviço, contacte-nos em:',
    'terms.contact.email': 'Email:',
    'terms.contact.address': 'Morada:',
    
    // Footer
    'footer.description': 'Conectando comunidades da diáspora através de intercâmbio cultural, educação e apoio.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.resources': 'Recursos',
    'footer.contact': 'Contacte-nos',
    'footer.copyright': 'Todos os direitos reservados.',
    'footer.cookies.text': 'Este website utiliza cookies para melhorar a experiência do utilizador. Ao continuar a navegar no site, concorda com o uso de cookies.',
    'footer.cookies.learnMore': 'Saber mais',
    'footer.cookies.accept': 'Aceitar',
    'footer.cookies.decline': 'Recusar',

    // Common
    'common.all': 'Todos',
    'common.loading': 'A carregar...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.view': 'Ver',
    'common.share': 'Partilhar',
    'common.like': 'Gostar',
    'common.comment': 'Comentar',
    'common.readMore': 'Ler Mais',
    'common.showMore': 'Mostrar Mais',
    'common.showLess': 'Mostrar Menos',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};